<?php

/**
 * File containing the EZTube function definitions.
 *
 * @copyright //autogen//
 * @license //autogen//
 * @version //autogen//
 */

$FunctionList = array();
$FunctionList['playlist'] = array( 'name' => 'playlist',
					'operation_types' => array( 'read' ),
					'call_method' => array( 'include_file' => 'extension/eztube/classes/eztube.php',
								'class' => 'EZTube',
								'method' => 'getPlaylistVideoFeed' ),	
					'parameter_type' => 'standard',
					'parameters' => array(	array('name' => 'playlist_id',
									'type' => 'string',
                                                               		'required' => true),
								array( 'name' => 'offset',
									'type' => 'integer',
									'required' => false,
									'default' => false ),
								array( 'name' => 'limit',
                                                                     	'type' => 'integer',
                                                                     	'required' => false,
                                                                     	'default' => false ),
								array('name' => 'order',
                                                                     	'type' => 'string',
                                                                     	'required' => false,
                                                                     	'default' => 'position' )));

$FunctionList['playlists'] = array( 'name' => 'playlists',
					'operation_types' => array( 'read' ),
					'call_method' => array( 'include_file' => 'extension/eztube/classes/eztube.php',
								'class' => 'EZTube',
								'method' => 'getPlaylistListFeed' ),	
					'parameter_type' => 'standard',
					'parameters' => array(	array('name' => 'user_id',
									'type' => 'string',
                                                               		'required' => true),
								array( 'name' => 'offset',
									'type' => 'integer',
									'required' => false,
									'default' => false ),
								array( 'name' => 'limit',
                                                                     	'type' => 'integer',
                                                                     	'required' => false,
                                                                     	'default' => false )));
                                                                     
$FunctionList['favorites'] = array( 'name' => 'favorites',
					'operation_types' => array( 'read' ),
					'call_method' => array( 'include_file' => 'extension/eztube/classes/eztube.php',
								'class' => 'EZTube',
								'method' => 'getUserFavorites' ),	
					'parameter_type' => 'standard',
					'parameters' => array(	array('name' => 'user_id',
									'type' => 'string',
                                                               		'required' => true),
								array( 'name' => 'offset',
									'type' => 'integer',
									'required' => false,
									'default' => false ),
								array( 'name' => 'limit',
                                                                     	'type' => 'integer',
                                                                     	'required' => false,
                                                                     	'default' => false ),
								array('name' => 'order',
                                                                     	'type' => 'string',
                                                                     	'required' => false,
                                                                     	'default' => 'relevance' )));

$FunctionList['uploads'] = array( 'name' => 'uploads',
					'operation_types' => array( 'read' ),
					'call_method' => array( 'include_file' => 'extension/eztube/classes/eztube.php',
								'class' => 'EZTube',
								'method' => 'getUserUploads' ),	
					'parameter_type' => 'standard',
					'parameters' => array(	array('name' => 'user_id',
									'type' => 'string',
                                                               		'required' => true),
								array( 'name' => 'offset',
									'type' => 'integer',
									'required' => false,
									'default' => false ),
								array( 'name' => 'limit',
                                                                     	'type' => 'integer',
                                                                     	'required' => false,
                                                                     	'default' => false ),
								array('name' => 'order',
                                                                     	'type' => 'string',
                                                                     	'required' => false,
                                                                     	'default' => false )));
$FunctionList['profile'] = array( 'name' => 'profile',
					'operation_types' => array( 'read' ),
					'call_method' => array( 'include_file' => 'extension/eztube/classes/eztube.php',
								'class' => 'EZTube',
								'method' => 'getUserProfile' ),	
					'parameter_type' => 'standard',
					'parameters' => array(	array('name' => 'user_id',
									'type' => 'string',
                                                               		'required' => true),
								array( 'name' => 'minimal',
									'type' => 'integer',
									'required' => false,
									'default' => false )));
$FunctionList['contacts'] = array( 'name' => 'uploads',
					'operation_types' => array( 'read' ),
					'call_method' => array( 'include_file' => 'extension/eztube/classes/eztube.php',
								'class' => 'EZTube',
								'method' => 'getContactFeed' ),	
					'parameter_type' => 'standard',
					'parameters' => array(	array('name' => 'user_id',
									'type' => 'string',
                                                               		'required' => true),
								array( 'name' => 'offset',
									'type' => 'integer',
									'required' => false,
									'default' => false ),
								array( 'name' => 'limit',
                                                                     	'type' => 'integer',
                                                                     	'required' => false,
                                                                     	'default' => false ),
								array('name' => 'order',
                                                                     	'type' => 'string',
                                                                     	'required' => false,
                                                                     	'default' => 'title' )));
$FunctionList['video'] = array( 'name' => 'video',
					'operation_types' => array( 'read' ),
					'call_method' => array( 'include_file' => 'extension/eztube/classes/eztube.php',
								'class' => 'EZTube',
								'method' => 'getVideoEntry' ),	
					'parameter_type' => 'standard',
					'parameters' => array(	array('name' => 'video_id',
									'type' => 'string',
                                                               		'required' => true ),
								array( 'name' => 'minimal',
									'type' => 'boolean',
									'required' => false,
									'default' => false )));
$FunctionList['comments'] = array( 'name' => 'comments',
					'operation_types' => array( 'read' ),
					'call_method' => array( 'include_file' => 'extension/eztube/classes/eztube.php',
								'class' => 'EZTube',
								'method' => 'getVideoCommentFeed' ),	
					'parameter_type' => 'standard',
					'parameters' => array(	array('name' => 'video_id',
									'type' => 'string',
                                                               		'required' => true),
								array( 'name' => 'offset',
									'type' => 'integer',
									'required' => false,
									'default' => false ),
								array( 'name' => 'limit',
                                                                     	'type' => 'integer',
                                                                     	'required' => false,
                                                                     	'default' => false ),
								array('name' => 'order',
                                                                     	'type' => 'string',
                                                                     	'required' => false,
                                                                     	'default' => 'published' )));
$FunctionList['responses'] = array( 'name' => 'responses',
					'operation_types' => array( 'read' ),
					'call_method' => array( 'include_file' => 'extension/eztube/classes/eztube.php',
								'class' => 'EZTube',
								'method' => 'getVideoResponseFeed' ),	
					'parameter_type' => 'standard',
					'parameters' => array(	array('name' => 'video_id',
									'type' => 'string',
                                                               		'required' => true),
								array( 'name' => 'offset',
									'type' => 'integer',
									'required' => false,
									'default' => false ),
								array( 'name' => 'limit',
                                                                     	'type' => 'integer',
                                                                     	'required' => false,
                                                                     	'default' => false ),
								array('name' => 'order',
                                                                     	'type' => 'string',
                                                                     	'required' => false,
                                                                     	'default' => 'relevance' )));
$FunctionList['related'] = array( 'name' => 'related',
					'operation_types' => array( 'read' ),
					'call_method' => array( 'include_file' => 'extension/eztube/classes/eztube.php',
								'class' => 'EZTube',
								'method' => 'getRelatedVideoFeed' ),	
					'parameter_type' => 'standard',
					'parameters' => array(	array('name' => 'video_id',
									'type' => 'string',
                                                               		'required' => true),
								array( 'name' => 'offset',
									'type' => 'integer',
									'required' => false,
									'default' => false ),
								array( 'name' => 'limit',
                                                                     	'type' => 'integer',
                                                                     	'required' => false,
                                                                     	'default' => false ),
								array('name' => 'order',
                                                                     	'type' => 'string',
                                                                     	'required' => false,
                                                                     	'default' => 'relevance' )));
$FunctionList['tags'] = array( 'name' => 'related',
					'operation_types' => array( 'read' ),
					'call_method' => array( 'include_file' => 'extension/eztube/classes/eztube.php',
								'class' => 'EZTube',
								'method' => 'fetchVideosByTags' ),	
					'parameter_type' => 'standard',
					'parameters' => array(	array('name' => 'tags',
									'type' => 'string',
                                                               		'required' => true),
								array( 'name' => 'offset',
									'type' => 'integer',
									'required' => false,
									'default' => false ),
								array( 'name' => 'limit',
                                                                     	'type' => 'integer',
                                                                     	'required' => false,
                                                                     	'default' => false ),
								array('name' => 'order',
                                                                     	'type' => 'string',
                                                                     	'required' => false,
                                                                     	'default' => false )));
$FunctionList['search'] = array( 'name' => 'related',
					'operation_types' => array( 'search' ),
					'call_method' => array( 'include_file' => 'extension/eztube/classes/eztube.php',
								'class' => 'EZTube',
								'method' => 'searchYouTube' ),	
					'parameter_type' => 'standard',
					'parameters' => array(	array('name' => 'keywords',
									'type' => 'string',
                                                               		'required' => false ),
                                                               	array('name' => 'searchtype',
									'type' => 'string',
                                                               		'required' => false,
                                                               		'default' => 'videos'),
                                                               	array('name' => 'filters',
									'type' => 'boolean',
                                                               		'required' => false,
                                                               		'default' => true ),
                                                               	array('name' => 'params',
									'type' => 'array',
									'required' => false ),
								array( 'name' => 'offset',
									'type' => 'integer',
									'required' => false,
									'default' => false ),
								array( 'name' => 'limit',
                                                                     	'type' => 'integer',
                                                                     	'required' => false,
                                                                     	'default' => false ),
								array( 'name' => 'order',
                                                                     	'type' => 'string',
                                                                     	'required' => false,
                                                                     	'default' => 'relevance' ) ) );
$FunctionList['standard'] = array( 'name' => 'related',
					'operation_types' => array( 'read' ),
					'call_method' => array( 'include_file' => 'extension/eztube/classes/eztube.php',
								'class' => 'EZTube',
								'method' => 'getStandardFeeds' ),	
					'parameter_type' => 'standard',
					'parameters' => array(	array('name' => 'type',
									'type' => 'string',
                                                               		'required' => true,
                                                               		'default' => 'rated'),
                                                               	array('name' => 'time',
									'type' => 'string',
                                                               		'required' => false ),
                                                               	array('name' => 'region',
									'type' => 'string',
									'required' => false ),
								array( 'name' => 'category',
									'type' => 'string',
									'required' => false ),
								array( 'name' => 'limit',
                                                                     	'type' => 'integer',
                                                                     	'required' => false,
                                                                     	'default' => 10 ) ) );
$FunctionList['categories'] = array( 'name' => 'categories',
					'operation_types' => array( 'read' ),
					'call_method' => array( 'include_file' => 'extension/eztube/classes/eztube.php',
								'class' => 'EZTube',
								'method' => 'getAvailableCategories' ),	
					'parameter_type' => 'standard',
					'parameters' => array(	array('name' => 'language',
									'type' => 'string',
                                                               		'required' => false )));




?>
